import { ACTION_TYPES } from '../../IDConstants'

const RDMActionTypes = {
  'Riposte': ACTION_TYPES.GCD,
  'Jolt': ACTION_TYPES.GCD,
  'Verthunder': ACTION_TYPES.GCD,
  'Veraero': ACTION_TYPES.GCD,
  'Scatter': ACTION_TYPES.GCD,
  'Verthunder II': ACTION_TYPES.GCD,
  'Veraero II': ACTION_TYPES.GCD,
  'Verfire': ACTION_TYPES.GCD,
  'Verstone': ACTION_TYPES.GCD,
  'Zwerchhau': ACTION_TYPES.GCD,
  'Redoublement': ACTION_TYPES.GCD,
  'Moulinet': ACTION_TYPES.GCD,
  'Vercure': ACTION_TYPES.oGCD,
  'Jolt II': ACTION_TYPES.GCD,
  'Verraise': ACTION_TYPES.GCD,
  'Impact': ACTION_TYPES.GCD,
  'Reprise': ACTION_TYPES.GCD,
  'Verthunder III': ACTION_TYPES.GCD,
  'Veraero III': ACTION_TYPES.GCD,
  'Enchanted Riposte': ACTION_TYPES.GCD,
  'Enchanted Zwerchhau': ACTION_TYPES.GCD,
  'Enchanted redoublement': ACTION_TYPES.GCD,
  'Enchanted Moulinet': ACTION_TYPES.GCD,
  'Enchanted Reprise': ACTION_TYPES.GCD,
  'Scorch': ACTION_TYPES.GCD,
  'Verflare': ACTION_TYPES.GCD,
  'Verholy': ACTION_TYPES.GCD,
  'Resolution': ACTION_TYPES.GCD,

  'Corps-a-corps': ACTION_TYPES.oGCD,
  'Displacement': ACTION_TYPES.oGCD,
  'Engagement': ACTION_TYPES.oGCD,
  'Fleche': ACTION_TYPES.oGCD,
  'Acceleration': ACTION_TYPES.oGCD,
  'Contre Sixte': ACTION_TYPES.oGCD,
  'Embolden': ACTION_TYPES.oGCD,
  'Manafication': ACTION_TYPES.oGCD,
  'Magick Barrier': ACTION_TYPES.oGCD,
}

export default RDMActionTypes
